# Generated by Django 5.2.7 on 2025-10-29 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField()),
                ('block_type', models.CharField(choices=[('paragraph', 'Paragraph'), ('heading', 'Heading'), ('table', 'Table'), ('form', 'Form'), ('list', 'List'), ('handwriting', 'Handwriting'), ('image', 'Image'), ('signature', 'Signature'), ('other', 'Other')], max_length=20)),
                ('text_content', models.TextField(blank=True)),
                ('bbox_x1', models.FloatField()),
                ('bbox_y1', models.FloatField()),
                ('bbox_x2', models.FloatField()),
                ('bbox_y2', models.FloatField()),
                ('confidence', models.FloatField(default=1.0)),
                ('is_handwritten', models.BooleanField(default=False)),
                ('requires_review', models.BooleanField(default=False)),
                ('table_data', models.JSONField(blank=True, default=dict)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['page', 'block_number'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('scanned', 'Scanned Document')], max_length=20)),
                ('file_size', models.IntegerField()),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_pages', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_label', models.CharField(blank=True, max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('select', 'Select'), ('date', 'Date'), ('signature', 'Signature'), ('other', 'Other')], max_length=20)),
                ('field_value', models.TextField(blank=True)),
                ('is_filled', models.BooleanField(default=False)),
                ('field_order', models.IntegerField(default=0)),
                ('confidence', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='documents.contentblock')),
            ],
            options={
                'ordering': ['content_block', 'field_order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/%Y/%m/%d/')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('detected_rotation', models.IntegerField(default=0)),
                ('applied_rotation', models.IntegerField(default=0)),
                ('detected_language', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla'), ('bn+en', 'Bangla + English'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('language_confidence', models.FloatField(default=0.0)),
                ('page_type', models.CharField(blank=True, max_length=50)),
                ('processed', models.BooleanField(default=False)),
                ('dpi', models.IntegerField(default=150)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.document')),
            ],
            options={
                'ordering': ['document', 'page_number'],
                'unique_together': {('document', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='ExtractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_data', models.JSONField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time', models.FloatField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('retry_count', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_logs', to='documents.document')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraction_logs', to='documents.page')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='contentblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='documents.page'),
        ),
        migrations.CreateModel(
            name='TableCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('column_path', models.JSONField()),
                ('text', models.TextField(blank=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('rowspan', models.IntegerField(default=1)),
                ('colspan', models.IntegerField(default=1)),
                ('is_header', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_cells', to='documents.contentblock')),
            ],
            options={
                'ordering': ['content_block', 'row_index', 'column_path'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='contentblock',
            unique_together={('page', 'block_number')},
        ),
    ]
