# Generated by Django 5.2.7 on 2025-10-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/original/%Y/%m/%d/'),
        ),
    ]
